# CONFIG/ USER INPUT:

# RELATIVE PATH DIRECTORY TO CONSTRICT LLM MODEL 
# !!!! DO NOT GIVE ACESS TO FOLDERS THAT YOU DONT HAVE BACKED UP AND SAVED OR CONTAIN ANYTHING SENSITIVE
# ONLY GIVE ACCESS TO THE FOLDER NECESSARY 
# !!!! LLM HAS WRITE ACESS TO FILES SO DO NOT GIVE ACCESSS HAPHAZARDLY ONCE AGAIN!!!!
WORKING_DIR = "./calculator"      # relative path 


# CONSTANTS

## LIMITS

### LLM AGENT LOOP ITERATION LIMITS:
AGENT_LOOP_ITERATION_LIMIT = 20


### CHARACTER LIMITS:
LLM_Read_Characater_Limit = 10000


### CODE FILE EXECUTION LIMITS:

Py_File_Execution_Time_Limit = 30 # in seconds 

